# URL k?t n?i: hrm_db là tên database b?n t?o trong pgAdmin
spring.datasource.url=jdbc:postgresql://localhost:5432/hrm_db
spring.datasource.username=postgres
spring.datasource.password=123456

# Driver cho PostgreSQL
spring.datasource.driver-class-name=org.postgresql.Driver

# T? ??ng t?o/c?p nh?t b?ng t? code Java (Entity) c?a b?n
spring.jpa.hibernate.ddl-auto=update

# Hi?n th? câu l?nh SQL ra console ?? d? debug
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true