spring.application.name=coursemanagement
# ===============================
# DATABASE (PostgreSQL)
# ===============================
# Thay ??i username và password cho kh?p v?i c?u hình Postgres trên máy c?a b?n
spring.datasource.url=jdbc:postgresql://localhost:5432/course_management
spring.datasource.username=postgres
spring.datasource.password=123456

# ===============================
# JPA / HIBERNATE
# ===============================
# T? ??ng c?p nh?t schema database d?a trên các class @Entity
spring.jpa.hibernate.ddl-auto=update

# ===============================
# SQL LOG
# ===============================
# In ra console các câu l?nh SQL mà Hibernate t? ??ng generate
spring.jpa.show-sql=true

spring.jpa.properties.hibernate.format_sql=true
# Disable OSIV warning
spring.jpa.open-in-view=false