server:
  port: 8081

spring:
  application:
    name: order-service

  # Cấu hình H2 Database (in-memory) để chạy thử
  datasource:
    url: jdbc:h2:mem:orderdb
    driver-class-name: org.h2.Driver
    username: sa
    password:

  h2:
    console:
      enabled: true       # Truy cập http://localhost:8081/h2-console để xem DB
      path: /h2-console

  jpa:
    hibernate:
      ddl-auto: update    # Tự tạo/cập nhật bảng theo Entity
    show-sql: true
    properties:
      hibernate:
        format_sql: true
