server:
  port: 8085

spring:
  application:
    name: order-service

  datasource:
    url: jdbc:postgresql://localhost:5432/order_db
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update      # tự tạo bảng orders trong order_db
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

# Không trả về stack trace mặc định của Spring trong response
server.error:
  include-stacktrace: never
  include-message: never
